---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gemini

resources:
  - namespace.yaml
  - storage.yaml
  - agate.yaml
  - ddclient-config.yaml
  - ddclient-sealedsecret.yaml
  - ddclient-deployment.yaml
