apiVersion: v1
kind: ConfigMap
metadata:
  name: pocket-id-config
  namespace: pocket-id
  labels:
    app.kubernetes.io/name: pocket-id
    app.kubernetes.io/part-of: utilities
    app.kubernetes.io/managed-by: argocd
data:
  APP_URL: "https://auth.mulliken.net"
  PORT: "1411"
  TRUST_PROXY: "true"
  ALLOW_USER_SIGNUPS: "disabled"
