$ANSIBLE_VAULT;1.1;AES256
66306133333138313836323163306133336465646161633836333462373763356563323565653139
3864313234323435633332373462396530653937346137640a323266646163336365623062616664
61326533373431396562376163643562363761353263373262656435383930366231633136333663
6138326433386662660a366130336461356665306461626164653838363165643930333736623730
32653836316432613837646636383931363464353737643161353664656236656634663731636239
62663963363061386466363936613063363739393831653836656230393363613530323036386136
61346664623764623636353866343764353437646537643061663438316164666366366266313866
33373961633266366661333263386263326362306638303833303337313138653034333139643164
66663365323666666238343763363130636534306566303136386437353736313165343337373062
32663230663730323066613236353831356462383564306238613736383465623134626161623939
646666386335316138623365383830656262
