$ANSIBLE_VAULT;1.1;AES256
36323938396162393066626236633531323132383064383161323364326239666334616436323834
3538323739316331346233656533306337633735333234300a626233383333326234313964653836
37653430333635376138313462326430303939323763336533633934643133366338333731666537
6631656631653436300a383763316437376564396433346465643263313261366333623262656635
39356432303664646661643563353835316139356666396230353633643736326563303637666564
66623562343362383362663766393838346236666261316232623064613939653864643330633830
30316365363531626335646139313136646630653031303038353566663730626431313939626438
39366636383465353831316161663630346664633163646663656536623436653533313438653638
63653463636133616363663438346237353065623862383033383566386633386239613035353830
32343265633365313233383933363032313962376131313332316534383130313365656566646334
66333632633837613733303465646562336435643365366662316663646131653562306266333662
64373831653537346166646230323539613736306131303863636333363435373139383665313837
62396461393562656335313265333438306335646662646663643831373137663334
