---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sabnzbd

resources:
  - namespace.yaml
  - sealedsecret.yaml
  - storage.yaml
  - sabnzbd.yaml
  - certificate.yaml
  - ingress.yaml
