---
- name: Restart squid
  ansible.builtin.systemd:
    name: squid
    state: restarted
  become: true

- name: Reload squid
  ansible.builtin.systemd:
    name: squid
    state: reloaded
  become: true
