---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sonarr

resources:
  - namespace.yaml
  - sealedsecret.yaml
  - storage.yaml
  - downloads.yaml
  - sonarr.yaml
  - radarr.yaml
  - certificate.yaml
  - ingress.yaml
