---
# Paperless Service
apiVersion: v1
kind: Service
metadata:
  name: paperless
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless
    app.kubernetes.io/instance: paperless
    app.kubernetes.io/part-of: documents
    app.kubernetes.io/component: app
    app.kubernetes.io/managed-by: argocd
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: paperless
    app.kubernetes.io/instance: paperless


