---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperless

resources:
  - namespace.yaml
  - secrets
  - postgres
  - redis
  - app
  - public-certificate.yaml
  - public-ingress.yaml
