---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: paperless-postgres
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless-postgres
    app.kubernetes.io/instance: paperless
    app.kubernetes.io/part-of: documents
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: argocd
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app.kubernetes.io/name: paperless-postgres
    app.kubernetes.io/instance: paperless


