---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: posthog
  namespace: posthog
  labels:
    app.kubernetes.io/name: posthog
    app.kubernetes.io/managed-by: argocd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - posthog.corp.mulliken.net
      secretName: posthog-tls
  rules:
    - host: posthog.corp.mulliken.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: posthog-web
                port:
                  number: 8000
