---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: posthog

helmCharts:
  - name: posthog
    repo: https://posthog.github.io/charts-clickhouse/
    version: 2025.1.1
    releaseName: posthog
    namespace: posthog
    valuesFile: values.yaml

resources:
  - certificate.yaml
  - ingress.yaml
