---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ddclient-config
  namespace: gemini
  labels:
    app.kubernetes.io/name: agate
    app.kubernetes.io/component: ddclient
    app.kubernetes.io/managed-by: argocd
data:
  ddclient.conf: |
    daemon=300
    syslog=yes
    ssl=yes

    # Cloudflare configuration
    protocol=cloudflare
    zone=mulliken.net
    ttl=1
    usev4=webv4, webv4=ipify-ipv4
    password_env=CLOUDFLARE_API_TOKEN
    gemini.mulliken.net