---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: paperless
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/component: tunnel
    app.kubernetes.io/managed-by: argocd
data:
  config.yaml: |
    tunnel: paperless-tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: paperless.mulliken.net
      service: http://paperless.paperless.svc.cluster.local:8000
    - service: http_status:404


