---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personal-site
  namespace: personal-site
  labels:
    app.kubernetes.io/name: personal-site
    app.kubernetes.io/part-of: utilities
    app.kubernetes.io/managed-by: argocd
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - mulliken.net
      secretName: personal-site-tls
  rules:
    - host: mulliken.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-site
                port:
                  number: 80
