---
apiVersion: v1
kind: Service
metadata:
  name: personal-site
  namespace: personal-site
  labels:
    app.kubernetes.io/name: personal-site
    app.kubernetes.io/part-of: utilities
    app.kubernetes.io/managed-by: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: personal-site
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
