---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperless

resources:
  - namespace.yaml
  - sealedsecrets.yaml
  - storage.yaml
  - paperless.yaml
  - cloudflare-tunnel.yaml
