---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: perses
  namespace: monitoring
  labels:
    app.kubernetes.io/name: perses
    app.kubernetes.io/instance: perses
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/component: ingress
    app.kubernetes.io/managed-by: argocd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - perses.corp.mulliken.net
      secretName: perses-tls
  rules:
    - host: perses.corp.mulliken.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: perses
                port:
                  number: 8080
