---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jellyfin

resources:
  - namespace.yaml
  - sealedsecret.yaml
  - storage.yaml
  - jellyfin.yaml
  - certificate.yaml
  - ingress.yaml
  - cloudflare-tunnel.yaml
