---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: umami

resources:
  - namespace.yaml
  - postgresql.yaml
  - umami.yaml
  - public-certificate.yaml
  - public-ingress.yaml
