---
# Handlers for rpi_setup role

- name: restart iscsi services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  with_items:
    - iscsid
    - iscsi
  become: true

- name: restart k3s
  ansible.builtin.systemd:
    name: k3s
    state: restarted
  become: true 
