---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - storage.yaml
  - configmap.yaml
  - victoria-metrics.yaml
  - kube-state-metrics.yaml
  - certificate.yaml
  - ingress.yaml
