---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCmSS3tFYViHY/syv6QsQAX92JmH2pSJva0H9pYNbudxMQ0f3bIawlgE+SAcgbr7QZEi6T3kFO9gcZzxt5mSnmA5fsj6GFWEKSLGTjj4dwL1oVB5wgUZk9RfCFHQTOD7UNooP4VVlMeWRUdvAedabYlotS/sUHbNjvwQC9ksSffAHTmjdipDORCApi+aeUpLnCgNc845K6rBYN4sQ3HBPdJRZxadlw/3nCPRxvyR0Edwl153TiYe6cJqstDil/c0BdFuNwLBjbB0NkfVWkMJsZwkexVn6C2YvUOt/tPkSWccZD/cSl6i82dxXPtvLiVI/zOLoLtbSGUU7Md+TNyawE0pjgRdn9srUQvfNQtBchWHYSqz+qkICj+UKfvmicmMyedhp3oRwVgfIwQMSKzx4WxfSIs1fB94Vtjcti6vK6zs++4JisSvGY7qvtTzo65b3oI4wgqnHdMSTbPJJ4xPgvb8HR1HqdvGrBred+uSdIEKcheW5Xc80UCJ+5nHolVjdgGtj88LuufdCzC0HQMnEJq/o/Xays8E1xIEnPqPKpILpHM2BqY96NrsMDEj/xFHMNftcBtBeuesyI/TjBFrKDEnFDPOgrYQMDSAgnwsePJs9OrX+mSbSzEzUl2f7BWwLbRCGFKlVAcftheJ7alnj3ngB5ZLilXSx6Lf3zseygMKeRf6jVQtgZNQRMgfjoAcuI6xz+yT+35/er8NWh5Kk93A+GCswYZgRg=
    admin-user: AgAy0km8JcCIOolOTldHQI5cphBXTn0DSr5wbRZqH/gPk0Ex2yhQ/4yKh89yNDSjvbDYjYuly3jajcISmobRkuyzXQoQHnBu/lsvrq6a+cV2BLrCk0ZaObO3QWW+I8ocfvsBFneWcj6Ek/r1Ee7e40a2Kr39JoJq5ilLTrus0BVxuaqgtD56AyU2dkLB+RhvUEy8zdWM7syZm/8l1RvUBC0XXdJpHDn5bHo88m9uoSgwBmitB5XVyY1MAXuoQmLt9EthliFJofh1osQ+um8YDG2oRqzKkqKj5WJwKmf30MsUiNUTwQyrQpj//crGrkESc8qXYwE8v7CpAfOS3CXXPoW+QfCph+hPrdu8IG9vSiv+c8cx78EpIGPlznBejS/k7EZSpsSfKDh2LE07Gw8Xgn03BlKzQs7mZhQd72vLlkg0A7xAczwiPdEEMKkg9zFd8ukB9jhYsAjzyP2EGJvA0CuhJtHgtg+Y4BRIJZCAwO7OpkkcCu7bhexfLeMI8C95k4krYJYubaVX6DczjWxNjfqU4f7y739OsygS8JJCfpfR42TpVCJwz6hG64Jf0M1L8qgHrpXjCHlYreOzxB7m3cm6+6jVFLwnk+t3wwHyOMrR5N51itT14EVlC5ZLnVSLNmqVEVXmipq8RAAadDQYMOI1BzUP5tU/cvy2oVZLM37YuUnnkr4rO0di099EoWk0h5mGjt6YBw==
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: ansible
        app.kubernetes.io/name: grafana
        app.kubernetes.io/part-of: observability
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
